services:
  db_mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_user_password
    ports:
      - "3306:3306"
    expose:
      - "3306"
  web:
    build: .
    volumes:
      - '.:/home/dev/code'
      - '/home/italo/.ssh:/home/dev/.ssh'
      - '/tmp/.X11-unix/:/tmp/.X11-unix/'
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_user_password
      DISPLAY: $DISPLAY
    depends_on:
      - db_mysql
    ports:
      - '8001:8001'
    stdin_open: true
    tty: true